version: 2.1
orbs:
  docker: circleci/docker@1.7.0
jobs:
  build:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push Docker image if on develop branch
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
              docker build -t ellik159/mylunar-config:latest .
              docker push ellik159/mylunar-config:latest
            else
              echo "Not on develop branch, skipping Docker build and push"
            fi
workflows:
  build_and_push:
    jobs:
      - build